task:
  video_only: false
  enable_thinking: false
  batch_size: 1
  parallel_qwen: false
  qwen_delay_s: 1.0
  max_retries: 3
  timeout: 180

model:
  qwen_model: qwen3-omni
  qwen_base_url: "http://10.62.186.36:8000/v1"
  qwen_api_key: EMPTY
  
sampling_params:
  temperature: 0.6
  top_p: 0.95
  top_k: 20
  max_tokens: 4096
  fps: 2.0
